import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GlassPane from "@/components/GlassPane";
import "../globals.css";
import clsx from "clsx";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Or Login Your Account",
  description: "Generated by create next app",
};

export default function AuthRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(" h-screen w-screen rainbow-mesh p-6", inter.className)}
      >
        <GlassPane className=" w-full h-full flex items-center justify-center">
          {children}
        </GlassPane>
      </body>
    </html>
  );
}
