import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GlassPane from "@/components/GlassPane";
import "../globals.css";
import clsx from "clsx";
import Sidebar from "@/components/Sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Or Login Your Account",
  description: "Generated by create next app",
};

export default function ProjectRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(" h-screen w-screen rainbow-mesh p-6", inter.className)}
      >
        <div className="flex items-center justify-between h-full w-full gap-4">
          <Sidebar />
          <GlassPane className=" w-full h-full flex items-center justify-center align-center container mx-auto">
            {children}
          </GlassPane>
        </div>
      </body>
    </html>
  );
}
